"""Add robust company fields

Revision ID: 7cd009be9873
Revises: bfb559778641
Create Date: 2026-07-25 00:08:46.026351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd009be9873'
down_revision: Union[str, Sequence[str], None] = 'bfb559778641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_contact',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_contact_company_id'), 'company_contact', ['company_id'], unique=False)
    op.create_table('company_note',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_note_company_id'), 'company_note', ['company_id'], unique=False)
    op.add_column('company', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('company', sa.Column('linkedin_url', sa.String(length=1024), nullable=True))
    op.add_column('company', sa.Column('glassdoor_url', sa.String(length=1024), nullable=True))
    op.add_column('company', sa.Column('tech_stack', sa.JSON(), nullable=True))
    op.add_column('company', sa.Column('benefits', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'benefits')
    op.drop_column('company', 'tech_stack')
    op.drop_column('company', 'glassdoor_url')
    op.drop_column('company', 'linkedin_url')
    op.drop_column('company', 'description')
    op.drop_column('company', 'size')
    op.drop_index(op.f('ix_company_note_company_id'), table_name='company_note')
    op.drop_table('company_note')
    op.drop_index(op.f('ix_company_contact_company_id'), table_name='company_contact')
    op.drop_table('company_contact')
    # ### end Alembic commands ###
