"""Add robust job fields

Revision ID: bfb559778641
Revises: ef08ca948138
Create Date: 2026-07-24 23:50:05.168890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb559778641'
down_revision: Union[str, Sequence[str], None] = 'ef08ca948138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('resume_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('job', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('job', sa.Column('seniority', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('benefits', sa.JSON(), nullable=True))
    op.add_column('job', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    op.add_column('job', sa.Column('ats_match_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index(op.f('ix_job_resume_id'), 'job', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'job', 'resume', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_index(op.f('ix_job_resume_id'), table_name='job')
    op.drop_column('job', 'ats_match_score')
    op.drop_column('job', 'rejection_reason')
    op.drop_column('job', 'benefits')
    op.drop_column('job', 'employment_type')
    op.drop_column('job', 'seniority')
    op.drop_column('job', 'source')
    op.drop_column('job', 'resume_id')
    # ### end Alembic commands ###
